/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author janio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmMain = new javax.swing.JPopupMenu();
        meCalculadora = new javax.swing.JMenuItem();
        mePedido = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menFun = new javax.swing.JMenu();
        menFunCad = new javax.swing.JMenuItem();
        menFunCal = new javax.swing.JMenuItem();
        menFunPed = new javax.swing.JMenuItem();
        menSob = new javax.swing.JMenu();
        menSobDes = new javax.swing.JMenuItem();
        menSai = new javax.swing.JMenu();
        menSaiSai = new javax.swing.JMenuItem();

        meCalculadora.setText("Calculadora");
        meCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                meCalculadoraMousePressed(evt);
            }
        });
        pmMain.add(meCalculadora);

        mePedido.setText("Pedido");
        mePedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mePedidoMousePressed(evt);
            }
        });
        pmMain.add(mePedido);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/um sistema para fazer o que quiser.png"))); // NOI18N

        lblUsuario.setText("Usuário: ");

        lblData.setText("Data:");

        menFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page.png"))); // NOI18N
        menFun.setText("Funções");

        menFunCad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menFunCad.setText("Cadastro");
        menFunCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menFunCadActionPerformed(evt);
            }
        });
        menFun.add(menFunCad);

        menFunCal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menFunCal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-png-calculator.png"))); // NOI18N
        menFunCal.setText("Calculadora");
        menFunCal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menFunCalMouseReleased(evt);
            }
        });
        menFunCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menFunCalActionPerformed(evt);
            }
        });
        menFun.add(menFunCal);

        menFunPed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menFunPed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-png-cadastro.png"))); // NOI18N
        menFunPed.setText("Pedido");
        menFunPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menFunPedActionPerformed(evt);
            }
        });
        menFun.add(menFunPed);

        Menu.add(menFun);

        menSob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/feed.png"))); // NOI18N
        menSob.setText("Sobre");
        menSob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menSobMousePressed(evt);
            }
        });

        menSobDes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menSobDes.setText("Descrição");
        menSobDes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menSobDesMousePressed(evt);
            }
        });
        menSobDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSobDesActionPerformed(evt);
            }
        });
        menSob.add(menSobDes);

        Menu.add(menSob);

        menSai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_out.png"))); // NOI18N
        menSai.setText("Sair");

        menSaiSai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menSaiSai.setText("Sair");
        menSaiSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSaiSaiActionPerformed(evt);
            }
        });
        menSai.add(menSaiSai);

        Menu.add(menSai);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblData)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(414, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menFunCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menFunCalActionPerformed
        Calculadora calculadora = new Calculadora();
        calculadora.setVisible(true);
    }//GEN-LAST:event_menFunCalActionPerformed

    private void menSaiSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSaiSaiActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        } 
    }//GEN-LAST:event_menSaiSaiActionPerformed

    private void menFunPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menFunPedActionPerformed
        Pedido pedido = new Pedido();
        pedido.setVisible(true);
    }//GEN-LAST:event_menFunPedActionPerformed

    private void menSobDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSobDesActionPerformed
        Descricao descricao = new Descricao();
        descricao.setVisible(true);
    }//GEN-LAST:event_menSobDesActionPerformed

    private void menFunCalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menFunCalMouseReleased
        //
    }//GEN-LAST:event_menFunCalMouseReleased

    private void meCalculadoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meCalculadoraMousePressed
        Calculadora calculadora = new Calculadora();
        calculadora.setVisible(true);
    }//GEN-LAST:event_meCalculadoraMousePressed

    private void mePedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mePedidoMousePressed
        Pedido pedido = new Pedido();
        pedido.setVisible(true);
    }//GEN-LAST:event_mePedidoMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if (evt.isPopupTrigger()) {
            pmMain.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseReleased

    private void menSobMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menSobMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menSobMousePressed

    private void menSobDesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menSobDesMousePressed
        Descricao descricao = new Descricao();
        descricao.setVisible(true);
    }//GEN-LAST:event_menSobDesMousePressed

    private void menFunCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menFunCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menFunCadActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // as linhas abaixo substituem a label lbldata pela data atual do sistema
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem meCalculadora;
    private javax.swing.JMenuItem mePedido;
    private javax.swing.JMenu menFun;
    private javax.swing.JMenuItem menFunCad;
    private javax.swing.JMenuItem menFunCal;
    private javax.swing.JMenuItem menFunPed;
    private javax.swing.JMenu menSai;
    private javax.swing.JMenuItem menSaiSai;
    private javax.swing.JMenu menSob;
    private javax.swing.JMenuItem menSobDes;
    private javax.swing.JPopupMenu pmMain;
    // End of variables declaration//GEN-END:variables
}
